### ISSUE TITLE
Support translations

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#225]
- [x] Load the plugin text domain (`wp-parsely`), since the plugin supports earlier than WP 4.6 (#268).
 - [x] Add internationalization functions to strings in PHP (#226).
 - [x] Fix `WordPress.WP.I18n` PHPCS violations, which includes the use of numbered placeholders, adding translator comments, and text strings not being a single string literal (avoid concatenations). Run `./vendor/bin/phpcs --standard=WordPress --sniffs=WordPress.WP.I18n . --ignore=vendor,node_modules -sp` to see what is outstanding (#226).
 - [x] Add internationalization functions to strings in JS (#236).
 - [x] Configure [ESLint rules](https://pascalbirchler.com/wordpress-javascript-i18n-eslint/) to check internationalized strings in JS (#183).
 - [x] ~Arrange translations from colleagues / Team Global to be added to translate.wordpress.org, and consider requesting them to be translation editors for this plugin (@GaryJones).~ Moving to post-2.5.0 release.

**Comment by jblz** [comment]
> Configure ESLint rules to check internationalized strings in JS.

While I was working on #236, eslint was not happy until I added a translator comment (per [@wordpress/i18n-translator-comments](https://github.com/WordPress/gutenberg/blob/trunk/packages/eslint-plugin/docs/rules/i18n-translator-comments.md)). 

Our setup extends `plugin:@wordpress/eslint-plugin/recommended-with-formatting` since #183, so we get the "recommended" settings by virtue:

https://github.com/Parsely/wp-parsely/blob/3cca62a4c228af6bd8893e744e710fb6b4269e94/.eslintrc#L3

**Comment by jblz** [comment]
Looks like all that's left here is to arrange translations!  Should we pull that out to the next milestone, @GaryJones?

**Comment by GaryJones** [comment]
> Looks like all that's left here is to arrange translations! Should we pull that out to the next milestone, @GaryJones?

Yes, happy to do that - we'd want to get this 2.5.0 release published so that translate.wordpress.org can enable translations anyway. Also, I've been chatting to the A8C Team Global, who have a way to get paid translations done.

**Comment by GaryJones** [comment]
> While I was working on #236, eslint was not happy until I added a translator comment (per [@wordpress/i18n-translator-comments](https://github.com/WordPress/gutenberg/blob/trunk/packages/eslint-plugin/docs/rules/i18n-translator-comments.md)).

Ah, I didn't realise it was already all configured!

One minor thing I've just spotted, is that the JS string of `<p ...>...</p>` should ideally have had the paragraph element moved outside of the string; I guess eslint doesn't check for that in the same way [WPCS does](https://github.com/WordPress/WordPress-Coding-Standards/blob/41f5a9c66ff814863bc479fb52fd6cd1abc87e28/WordPress/Sniffs/WP/I18nSniff.php#L674-L677). I opened #283 to look at this.
