### ISSUE TITLE
Implement Traffic Boost feature

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#2887]
This issue is about Implementing the Traffic Boost feature.

# Implementation phases

- [x] Determine the feasibility of the feature, and identify "what it takes" to land it
- [x] Implement the front-end
- [x] Implement the back-end
- [x] Launch internal beta testing stage
- [x] Release in wp-parsely 3.19.0 as a beta feature

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by acicovic** [comment]
This was implemented and merged.
